// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fast_factor
SEXP fast_factor(SEXP x, SEXP levs);
RcppExport SEXP corpustools_fast_factor(SEXP xSEXP, SEXP levsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type levs(levsSEXP);
    __result = Rcpp::wrap(fast_factor(x, levs));
    return __result;
END_RCPP
}
// count
std::map<String, int> count(SEXP x);
RcppExport SEXP corpustools_count(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    __result = Rcpp::wrap(count(x));
    return __result;
END_RCPP
}
// full_set_ids
IntegerVector full_set_ids(SEXP x);
RcppExport SEXP corpustools_full_set_ids(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    __result = Rcpp::wrap(full_set_ids(x));
    return __result;
END_RCPP
}
