# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_factor <- function(x, levs) {
    .Call('corpustools_fast_factor', PACKAGE = 'corpustools', x, levs)
}

count <- function(x) {
    .Call('corpustools_count', PACKAGE = 'corpustools', x)
}

full_set_ids <- function(x) {
    .Call('corpustools_full_set_ids', PACKAGE = 'corpustools', x)
}

