# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

collapse_terms_cpp <- function(term, collapse, sep = " ", sep2 = " ") {
    .Call('_corpustools_collapse_terms_cpp', PACKAGE = 'corpustools', term, collapse, sep, sep2)
}

uncollapse_terms_cpp <- function(term, sep = " ") {
    .Call('_corpustools_uncollapse_terms_cpp', PACKAGE = 'corpustools', term, sep)
}

do_code_dictionary <- function(feature, context, which, dict, verbose) {
    .Call('_corpustools_do_code_dictionary', PACKAGE = 'corpustools', feature, context, which, dict, verbose)
}

fast_factor_cpp <- function(x, levs) {
    .Call('_corpustools_fast_factor_cpp', PACKAGE = 'corpustools', x, levs)
}

AND_hit_ids_cpp <- function(con, subcon, pos, term_i, n_unique, group_i, replace, feature_mode) {
    .Call('_corpustools_AND_hit_ids_cpp', PACKAGE = 'corpustools', con, subcon, pos, term_i, n_unique, group_i, replace, feature_mode)
}

proximity_hit_ids_cpp <- function(con, subcon, pos, term_i, n_unique, window, seq_i, replace, feature_mode, directed) {
    .Call('_corpustools_proximity_hit_ids_cpp', PACKAGE = 'corpustools', con, subcon, pos, term_i, n_unique, window, seq_i, replace, feature_mode, directed)
}

sequence_hit_ids_cpp <- function(con, subcon, pos, term_i, length) {
    .Call('_corpustools_sequence_hit_ids_cpp', PACKAGE = 'corpustools', con, subcon, pos, term_i, length)
}

ngrams_cpp <- function(tokens, group, n, sep, empty) {
    .Call('_corpustools_ngrams_cpp', PACKAGE = 'corpustools', tokens, group, n, sep, empty)
}

parse_query_cpp <- function(x) {
    .Call('_corpustools_parse_query_cpp', PACKAGE = 'corpustools', x)
}

