# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_factor <- function(x, levs) {
    .Call('_corpustools_fast_factor', PACKAGE = 'corpustools', x, levs)
}

proximity_hit_ids <- function(con, subcon, pos, term_i, n_unique, window, seq_i, replace, feature_mode, directed) {
    .Call('_corpustools_proximity_hit_ids', PACKAGE = 'corpustools', con, subcon, pos, term_i, n_unique, window, seq_i, replace, feature_mode, directed)
}

AND_hit_ids <- function(con, subcon, pos, term_i, n_unique, group_i, replace, feature_mode) {
    .Call('_corpustools_AND_hit_ids', PACKAGE = 'corpustools', con, subcon, pos, term_i, n_unique, group_i, replace, feature_mode)
}

sequence_hit_ids <- function(con, subcon, pos, term_i, length) {
    .Call('_corpustools_sequence_hit_ids', PACKAGE = 'corpustools', con, subcon, pos, term_i, length)
}

ngrams <- function(tokens, group, n, sep, empty) {
    .Call('_corpustools_ngrams', PACKAGE = 'corpustools', tokens, group, n, sep, empty)
}

parse_query <- function(x) {
    .Call('_corpustools_parse_query', PACKAGE = 'corpustools', x)
}

